- .github/workflows/unit-tests.yml
> fix: run tests on pull-requests

- .storybook/main.js
- package.json
- pnpm-lock.yaml
> fix: remove storybook migration assistant

- package.json
- pnpm-lock.yaml
- rollup.config.js
> fix: deprecated rollup plugin warning

- package.json
- rollup.config.js
- tsconfig.json
> fix: compile ts code to dist and exclude compiling utils

- .github/workflows/storybook-test.yml
Checklist:
We're not using the build artifacts, we're just using this to make sure that they can be created.
> refactor: clarify that the storybook workflow tests the build

- .github/workflows/storybook-deploy.yml
Testing requires me to do on push as well.
> feat: Deploy Storybook as documentation site

- .github/workflows/unit-tests.yml
- README.md
> ci: lint before testing

- .lintstagedrc.json
> chore: run prettier on commit

- .eslintrc.json
- package.json
- pnpm-lock.yaml
Checklist:
Closes #54
It's been added and the rules should only be applying to test files.
> feat: add eslint-plugin-jest

- src/alert/alert.stories.tsx
- src/button/button.stories.tsx
- src/close-button/close-button.stories.tsx
- src/col/col.stories.tsx
- src/container/container.stories.tsx
- src/control-label/control-label.stories.tsx
- src/drop-down/drop-down.stories.tsx
- src/form-control/form-control.stories.tsx
- src/form-group/form-group.stories.tsx
- src/help-block/help-block.stories.tsx
- src/image/image.stories.tsx
- src/link/link.stories.tsx
- src/modal/modal.stories.tsx
- src/panel/panel.stories.tsx
- src/row/row.stories.tsx
- src/table/table.stories.tsx
- src/tabs/tabs.stories.tsx
- src/toggle-button/toggle-button.stories.tsx
- utils/gen-component-template.ts
Checklist:
This PR makes the following changes to the Storybook sidebar:
- Renaming the "Example" section to "Components"
- Moving `ToggleButton` into the `WIP` section
| Before | After |
| --- | --- |
| <img width="1680" alt="Screenshot 2024-04-09 at 23 28 34" src="https://github.com/freeCodeCamp/ui/assets/25715018/1be80a65-6c83-46b6-826f-dc19fc7f8802"> | <img width="1680" alt="Screenshot 2024-04-09 at 23 16 24" src="https://github.com/freeCodeCamp/ui/assets/25715018/1e622fbc-d1dd-49c3-9ceb-2c30a5b3e85b"> |
> chore(storybook): reorganize component list

- src/image/image.tsx
Checklist:
#87 renamed `image.types.ts` to `types.ts`, but an import path wasn't updated to reflect the change. This PR fixes that.
Closes #88
> fix: import path

- package.json
- pnpm-lock.yaml
Checklist:
This PR:
- Removes `@types/testing-library__jest-dom`
- Upgrades `@testing-library/jest-dom`
`@types/testing-library__jest-dom` is an internal of `@testing-library/jest-dom`, and we don't need to consume it directly. Removing the package caused some type check errors, and upgrading `@testing-library/jest-dom` resolved them ¯\\\_(ツ)_/¯
> chore(deps): remove `@types/testing-library__jest-dom` and upgrade `@testing-library/jest-dom`

- package.json
> chore: release v1.0.0

- package.json
> chore: release v1.0.1

- package.json
> chore: release v1.0.2

- package.json
> chore: release v1.0.3

- src/drop-down/drop-down.tsx
> fix: add a top margin to DropDownButton

- src/drop-down/drop-down.tsx
Checklist:
Fixes the alignment of the dropdown icon.
| Before | After |
| --- | --- |
| <img width="249" alt="Screenshot 2024-07-18 at 12 59 37" src="https://github.com/user-attachments/assets/0e4232b7-7642-4071-8eb2-05409467133e"> | <img width="250" alt="Screenshot 2024-07-18 at 12 59 31" src="https://github.com/user-attachments/assets/8b692a74-4977-424e-9999-9f0b54f6dff8"> |
> fix: dropdown icon alignment

- package.json
Checklist:
I'm making a minor version bump because this release includes a new feature (#248).
> chore: release 1.1.0

- package.json
Checklist:
Bumps the version to 1.2.0 to roll out the new components.
> chore: bump version to 1.2.0

- package.json
Checklist:
Releases version 2.
This is a major version bump because https://github.com/freeCodeCamp/ui/pull/323 has some breaking changes.
> chore: bump version to 2.0.0

- src/quiz/use-quiz.test.ts
- src/quiz/use-quiz.ts
Checklist:
Related to https://github.com/freeCodeCamp/freeCodeCamp/pull/56163#discussion_r1777130354.
> feat: handle onSuccess and onFailure in useQuiz

- src/quiz/quiz.tsx
Checklist:
This PR updates the Quiz component to increase the space between questions.
Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/56805#pullrequestreview-2390842775.
> fix: adjust space between quiz questions

- .babelrc.js
Checklist:
Closes #https://github.com/freeCodeCamp/ui/issues/449
> fix: add jsx to babel highlight

- .babelrc.js
> Enable Bash syntax highlighting

- .storybook/main.ts
> fix: Color System page

- .storybook/main.ts
Checklist:
Adds fCC favicon to the storybook page.
| Before | After |
| --- | --- |
| <img width="241" alt="Screenshot 2025-03-14 at 14 43 24" src="https://github.com/user-attachments/assets/48b02726-bd96-41e2-9200-fbe4f3ee2835" /> | <img width="242" alt="Screenshot 2025-03-14 at 14 42 37" src="https://github.com/user-attachments/assets/043c0e34-6507-4f98-b378-3275fe05fa39" /> |
> feat(storybook): add fCC favicon

- src/control-label/control-label.tsx
> fix(control-label): set font weight to bold
